server:
  port: 9999
spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2
zuul:
  ribbon:
    eager-load:
      enabled: true
      clients: pig-auth,pig-upms-service,pig-demo-service
  ignoredServices: '*'
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  ratelimit:
    key-prefix: pig-ratelimite
    enabled: true
    repository: REDIS
    behind-proxy: true
    policies:
      pig-upms-service:
        limit: 100
        quota: 100
        refresh-interval: 3
security:
  encode:
    key: '1234567887654321'
  validate:
    code: false
    preview: true
  sessions: stateless
  oauth2:
    client:
      client-id: pig
      client-secret: pig
    resource:
      jwt:
        key-uri: ${security.auth.server}/oauth/token_key
ignore:
  urls:
    - /mobile/**
    - /auth/**
    - /admin/code/*
    - /admin/smsCode/*
    - /admin/user/info
    - /admin/menu/userMenu
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**
  clients:
    - app        
