server:
  port: 5003

# datasoureƒ¨»œ π”√JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zl199144
    url: jdbc:mysql://47.99.184.208:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

zipkin:
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5672
      password: zhuzhu123
      username: zhuzhu
      queue: zipkin
  storage:
    type: mysql
